swagger: "2.0"
info:
  title: Statista MCP - PROD
  description: Fetch Statista search and statistics data in PROD environment
  version: 0.1.0
host: api.statista.ai
basePath: /v1
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Statista MCP - PROD
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      security:
        - apiKey: []
      responses:
        "200":
          description: Success
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
