swagger: "2.0"
info:
  title: Statista MCP - STAGE
  description: Fetch Statista search and statistics data in STAGE environment
  version: 0.1.0
host: api.globalsearch.stage.aws.statista.com
basePath: /v1
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Statista MCP - STAGE
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      security:
        - apiKey: []
      responses:
        "200":
          description: Success
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
