name: CI/CD - PR code check

on:
  pull_request:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  code_checks:
    uses: ./.github/workflows/code_checks.yml

  build:
    needs: code_checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/prepare-tooling
      - name: Build typescript code
        shell: bash
        working-directory: ./
        run: npm run build
