name: Code Checks

on:
  workflow_call:

jobs:
  all:
    needs: [lint, lint-cdk, synth-cdk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: echo '${{ toJSON(needs) }}' | jq -e 'to_entries | all(.value.result == "success")'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/prepare-tooling
      - name: Run Prettier check
        run: npx prettier --check "**/*.{ts,js}"

  # CDK / Typescript
  lint-cdk:
    name: Lint CDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdk
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/prepare-tooling
      - name: Run Prettier check
        run: npx prettier --check "**/*.{ts,js}"

  synth-cdk:
    name: Synth CDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdk
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/prepare-tooling
      - name: Run CDK Synth
        run: npx cdk synth
